services:
  api:
    environment:
      APP_ENV: development
      DEBUG: "true"
    volumes:
      - .:/app:cached
      - ./data:/app/data

  worker:
    environment:
      APP_ENV: development
      DEBUG: "true"
    volumes:
      - .:/app:cached
      - ./data:/app/data

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
